remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "STDFormer: Spatio-Temporal Disentanglement Learning for 3D Human Mesh Recovery from Monocular Videos with Transformer"
description: "Anonymous"
show_downloads: false

github:
  zip_url: http://example.com/download.zip
  another_url: another value
